# Ref: https://github.com/serverless-components/tencent-scf/blob/master/docs/configure.md.
#应用组织信息
org: '' # 组织名称。留空则则使用默认值为用户appid
app: '' # 应用名称。留空则默认取当前组件的实例名称为app名称。
#stage: 'test' # 环境名称。默认值是 dev。建议使用${env.STAGE}变量定义环境名称
stage: ${env.STAGE} # 环境名称。默认值是 dev。建议使用${env.STAGE}变量定义环境名称

component: scf
name: timer-demo

inputs:
  src:
    src: ./
    hook: "ls"
    exclude:
      - .env
  region: ap-shanghai
  runtime: Go1
  handler: main
  description: ${name}
  memorySize: 128 # 内存大小，单位MB
  timeout: 1800 # 函数执行超时时间，单位秒
  initTimeout: 3 # 初始化超时时间，单位秒

  environment: #  环境变量
    variables: #  环境变量对象
      ENV: ${stage}
      AIRDB_DB_BBHJ_BBS_READ: "mina:Mina@123@tcp(sh-cdb-n7qw1jqg.sql.tencentcdb.com:62974)/dev_airdb"
      AIRDB_DB_MINA_API_WRITE: "mina:Mina@123@tcp(sh-cdb-n7qw1jqg.sql.tencentcdb.com:62974)/dev_airdb"
      AIRDB_DB_MINA_API_READ: "mina:Mina@123@tcp(sh-cdb-n7qw1jqg.sql.tencentcdb.com:62974)/dev_airdb"
  events:
    - timer:
        parameters:
          # !!!!! Please be aware, the second field should `0`, otherwise it will be run every second.
          # Sec, Min, Hour, Day, Month, Weekday, Year.
          # CronExpression: '*/1 * * * *'
          cronExpression: '0 */10 * * * * *'
          enable: True
